version: "3"
services:
  zmq:
    build:
      dockerfile: Dockerfile.one

  client:
    build:
      dockerfile: Dockerfile.two
    depends_on:
      - zmq
    deploy:
      mode: replicated
      replicas: 10
