version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: "Admin123"
      MYSQL_DATABASE: "go_fleet"
    volumes: 
      - ./testdb:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  zmq_router:
    build:
      dockerfile: Dockerfile.zmq_router
    environment:
      ZMQ_PORT: "5555"
      DS_NAME: "root:Admin123@tcp(db:3306)/go_fleet"
      MYSQL_HOST: "db"
      MYSQL_PASSWORD: "Admin123"
      MYSQL_DB: "go_fleet"
      MYSQL_USER: "root"
      MYSQL_PORT: "3306"
    depends_on:
      - db

  sensor_zmq:
    build:
      dockerfile: Dockerfile.sensor_zmq
    environment:
      ZMQ_CONNECTION: "tcp://zmq_router:5555"
      SENSOR_ID: "s0"
    depends_on:
      - zmq_router
