FROM golang:1.19-bullseye

EXPOSE 5555

RUN apt-get update \
  && apt-get install -y \
    libczmq-dev \
    default-mysql-client

RUN mkdir /build
WORKDIR /build
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN /bin/chmod +x /usr/local/bin/entrypoint.sh
RUN CGO_ENABLED=1 go build -o app cmd/zmq/zmq_router.go

RUN mv /build/app /usr/local/bin/
CMD ["app"]
ENTRYPOINT ["entrypoint.sh"]
