version: "3"
services:
  sensor_zmq_sub:
    image: ghcr.io/dragks/gofleet/sensor_zmq_sub:v0.1.0
    container_name: sensor_zmq_sub
    environment:
      ZMQ_SUB_ENDPOINT: "tcp://sensor_zmq_pub:5555"
      SAVE_ENDPOINT: "tcp://fluentd:20001"
      TOPIC: "sensor"
    links:
      - "sensor_zmq_pub"
      - "fluentd"
    depends_on:
      - "sensor_zmq_pub"
      - "fluentd"

  sensor_zmq_pub:
    image: ghcr.io/dragks/gofleet/sensor_zmq_pub:v0.1.0
    container_name: sensor_zmq_pub
    environment:
      ZMQ_PUB_ENDPOINT: "tcp://*:5555"
      TOPIC: "sensor"
    expose:
      - "5555"

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - elasticsearch
    expose:
      - "20001"
    ports:
      - "20001:20001/tcp" # sensor-data tcp

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    links:
      - elasticsearch
    expose:
      - "5601"
    ports:
      - "5601:5601"
