version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: "Admin123"
      MYSQL_DATABASE: "go_fleet"
    volumes: 
      - ./testdb:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  sensor_zmq_sub:
    build:
      dockerfile: Dockerfile.sensor_zmq_sub
    environment:
      ZMQ_SUB_ENDPOINT: "tcp://sensor_zmq_pub:5555"
      TOPIC: "sensor"
      DB_DRIVER: "mysql"
      DS_NAME: "root:Admin123@tcp(db:3306)/go_fleet"
      MYSQL_HOST: "db"
      MYSQL_PASSWORD: "Admin123"
      MYSQL_DB: "go_fleet"
      MYSQL_USER: "root"
      MYSQL_PORT: "3306"
    depends_on:
      - db
      - sensor_zmq_pub

  sensor_zmq_pub:
    build:
      dockerfile: Dockerfile.sensor_zmq_pub
    environment:
      ZMQ_PUB_ENDPOINT: "tcp://*:5555"
      TOPIC: "sensor"
      SENSOR_ID: "s0"
