FROM golang:1.19-bullseye as builder

RUN apt-get update \
  && apt-get install -y \
    libczmq-dev

RUN mkdir /build
WORKDIR /build
COPY ./go.mod .
COPY ./go.sum .
RUN go mod download
COPY . .
RUN CGO_ENABLED=1 go build -o app cmd/subscriber/sensor_zmq_sub.go

FROM debian:bullseye-slim

EXPOSE 5555

RUN apt-get update \
  && apt-get install -y \
    libczmq-dev

COPY --from=builder /build/app /usr/local/bin/
CMD ["app"]
