apiVersion: v1
kind: ConfigMap
metadata:
  name: sensor-zmq-config
  labels:
    app: fluentd
data:
  fluentd-host: tcp://fluentd-svc:5170
  topic: sensor
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sensor-zmq
  labels:
    app: sensor-zmq
spec:
  selector:
    matchLabels:
      app: sensor-zmq
  template:
    metadata:
      labels:
        app: sensor-zmq
    spec:
      containers:
        - name: sensor-zmq-pub
          image: ghcr.io/dragks/gofleet/sensor_zmq_pub:v0.1.0
          env:
            - name: ZMQ_PUB_ENDPOINT
              value: "tcp://*:5555"
            - name: TOPIC
              valueFrom:
                configMapKeyRef:
                  name: sensor-zmq-config
                  key: topic
          ports:
            - containerPort: 5555
        - name: sensor-zmq-sub
          image: ghcr.io/dragks/gofleet/sensor_zmq_sub:v0.1.0
          env:
            - name: ZMQ_SUB_ENDPOINT
              value: "tcp://localhost:5555"
            - name: SAVE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: sensor-zmq-config
                  key: fluentd-host
            - name: TOPIC
              valueFrom:
                configMapKeyRef:
                  name: sensor-zmq-config
                  key: topic
---
apiVersion: v1
kind: Service
metadata:
  name: sensor-zmq-pub-svc
  labels:
    app: sensor-zmq
spec:
  ports:
    - port: 5555
      protocol: TCP
      targetPort: 5555
  selector:
    app: sensor-zmq
