fluentdHost: "tcp://fluentd-svc:5170"
fluentdPort: "5170"
fluentdServiceName: "fluentd-svc"
topicName: "sensor"
zmqPubEndpoint: "tcp://*:5555"
zmqSubEndpoint: "tcp://sensor-zmq-pub-svc:5555"
pubServiceName: "sensor-zmq-pub-svc"
pubServicePort: "5555"
elasticsearchHost: "quickstart-es-default"
elasticsearchPort: "9200"
