apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-conf
  labels:
    app: fluentd
data:
  elasticsearch-host: {{ .Values.elasticsearchHost }}
  elasticsearch-port: "{{ .Values.elasticsearchPort }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentconf
  labels:
    app: fluentd
data:
  fluent.conf: |
    <source>
      @type tcp
      tag sensor-data # required
      <parse>
        @type regexp
        expression /^(?<topic>\w+):(?<value>\d+\.\d+)$/
        types topic:string
        types value:float
      </parse>
      port 5170   # optional. 5170 by default
      bind 0.0.0.0 # optional. 0.0.0.0 by default
      delimiter "\n" # optional. "\n" (newline) by default
    </source>

    <match *.**>
      @type copy

      <store>
        @type elasticsearch
        host "#{ENV['ELASTICSEARCH_HOST']}"
        port "#{ENV['ELASTICSEARCH_PORT']}"
        user "#{ENV['ELASTICSEARCH_USER_NAME']}"
        password "#{ENV['ELASTICSEARCH_USER_PASS']}"
        logstash_format true
        logstash_prefix fluentd
        logstash_dateformat %Y%m%d
        include_tag_key true
        type_name access_log
        tag_key @log_name
        flush_interval 1s
        scheme https
        ssl_verify false
      </store>

      <store>
        @type stdout
      </store>
    </match>
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fluentdServiceName }}
  labels:
    app: fluentd
spec:
  ports:
    - port: {{ .Values.fluentdPort }}
      protocol: TCP
      targetPort: 5170
  selector:
    app: fluentd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
          env:
            - name: ELASTICSEARCH_USER_NAME
              value: "elastic"
            - name: ELASTICSEARCH_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: quickstart-es-elastic-user
                  key: elastic
            - name: ELASTICSEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  name: fluentd-conf
                  key: elasticsearch-host
            - name: ELASTICSEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  name: fluentd-conf
                  key: elasticsearch-port
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: fluentconf
              mountPath: /fluentd/etc/
          ports:
            - containerPort: 5170
      terminationGracePeriodSeconds: 30
      volumes:
        - name: fluentconf
          configMap:
            name: fluentconf
